POST http://localhost:9808/create-short-url HTTP/1.1
content-type: application/json

{
    "long_url": "https://github.com/darkmelcof/GO_URL_SHORTENER",
    "user_id" : "e0dba740-fc4b-4977-872c-d360239e6b10"
}